"""Generate robots.txt from the tenant policy.

Two purposes:
1. Politely tell well-behaved crawlers what the policy already enforces.
2. Publish honeypot paths as Disallow entries — any client that fetches
   them anyway has proven it ignores robots.txt and is treated as
   hostile by the detector.
"""

from __future__ import annotations

from .policy import Policy
from .signatures import HONEYPOT_PATHS


def generate_robots(policy: Policy) -> str:
    lines = [
        "# Generated by ToriiGate — enforced at the gateway, not just requested.",
    ]
    for name in sorted(set(policy.blocked_ai_bot_names())):
        lines += [f"User-agent: {name}", "Disallow: /", ""]
    lines += ["User-agent: *"]
    for trap in HONEYPOT_PATHS:
        lines.append(f"Disallow: {trap}")
    lines.append("")
    return "\n".join(lines)
